on:
  pull_request_review:
    types: [submitted]


jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: "pr review request submitted"
              run: |
                echo "called"
